<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot">
		<!--
        <xacro:inertial_cylinder mass="0.1" length="0.04" radius="0.05">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
        -->
    <!--inertial.xacro 추가하기-->
    
    
        <!-- 
        	중력 무시해야할 경우 
			<gazebo reference="box_link1">
				<material>Gazebo/White</material>
				<turnGravityOff>true</turnGravityOff>
			</gazebo>
		-->
    <xacro:include filename="gazebo_control.xacro" />
	<xacro:include filename="lidar.xacro" />
	<xacro:include filename="camera.xacro" />
	<!-- color -->

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="red">
        <color rgba="1 0.1 0.1 1"/>
    </material>

    <material name="green">
        <color rgba="0.1 1 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.1 0.1 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

	<!--  Constants   -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="mass" value="1" /> 
  <xacro:property name="width" value="0.1" /> 
  <xacro:property name="height" value="0.1" /> <!-- Joint Link -->
  <xacro:property name="height1" value="2" /> <!-- Link 1 -->
  <xacro:property name="height2" value="1" /> <!-- Link 2 -->
  <xacro:property name="height3" value="1" /> <!-- Link 3 -->

  <!-- xacro:property name="camera_link" value="0.1" /--> 
  <!-- xacro:property name="axel_offset" value="0.1" /--> 

	<!-- link -->
	
	<!-- Info. world -> Y,R joint - link1 - R joint - link2  - R,P,Y joint - link3       -->
	<!-- joint type : rev , fixed -->
	
	<!-- link 0. world link -->
	
	<link name="world"> 
	
	</link>
	

	<joint name="joint0" type="revolute">
		<parent link="world"/>
		<child link="joint_link1"/>
		<origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
        <axis xyz="0 0 1" />
        <limit effort="100" velocity="0.1" lower="-${PI}" upper="${PI}"/>
        <dynamics damping="50" friction="1"/>
	</joint>
	
	
	<!-- joint 1. Yaw joint -->
	<link name="joint_link1">
		<visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <cylinder length="${height}" radius=".05" />
            </geometry>
            <material name="white"/>
        </visual>
        
		<collision>
			<origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
			<geometry>
				<cylinder length="${height}" radius=".05" />
			</geometry>
		</collision>
		
		<inertial>
            <mass value="${mass}"/>
            <inertia ixx="${1}" ixy="0.0" ixz="0.0" 
                iyy="${1}" iyz="0.0" 
                izz="${1}"/>
        </inertial>
	</link>
	
	
	<joint name="joint1" type="revolute">
		<parent link="joint_link1"/>
		<child link="joint_link2"/>
		<origin xyz="0 0 ${height}" rpy="${PI/2} 0 0"/>
        <axis xyz="0 0 1" />
        <limit effort="100" velocity="0.1" lower="-${PI}" upper="${PI}"/>
        <dynamics damping="50" friction="1"/>
	</joint>
	
	
		<!-- joint 2. Roll joint -->
	<link name="joint_link2">
		<visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <cylinder length="${height}" radius=".05" />
            </geometry>
            <material name="white"/>
        </visual>
        
		<collision>
			<origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
			<geometry>
				<cylinder length="${height}" radius=".05" />
			</geometry>
		</collision>
		
		<inertial>
            <mass value="${mass}"/>
            <inertia ixx="${1}" ixy="0.0" ixz="0.0" 
                iyy="${1}" iyz="0.0" 
                izz="${1}"/>
        </inertial>
	</link>
	
	<joint name="joint2" type="fixed">
		<parent link="joint_link2"/>
		<child link="box_link1"/>
		<origin  xyz="0 ${height1/2 + height/2} 0" rpy="-${PI/2} 0 0"/>
        <axis xyz="0 0 1" />
        <limit effort="100" velocity="0.1" lower="-${PI}" upper="${PI}"/>
        <dynamics damping="50" friction="1"/>
	</joint>
	
	
		<!-- link 1. box_link1 -->
	<link name="box_link1">
		<visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${width} ${width} ${height1}"/>
            </geometry>
            <material name="white"/>
        </visual>
        
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<box size="${width} ${width} ${height1}"/>
			</geometry>
		</collision>
		
		<inertial>
            <mass value="${mass}"/>
            <inertia ixx="${1}" ixy="0.0" ixz="0.0" 
                iyy="${1}" iyz="0.0" 
                izz="${1}"/>
        </inertial>
	</link>
	
	
	
	<joint name="joint3" type="revolute">
		<parent link="box_link1"/>
		<child link="joint_link3"/>
		<origin  xyz="0 0 ${height1/2 + height/2}" rpy="${PI/2} 0 0"/>
        <axis xyz="0 0 1" />
        <limit effort="100" velocity="0.1" lower="-${PI}" upper="${PI}"/>
        <dynamics damping="50" friction="1"/>
	</joint>
	
	
		<!-- link 1. joint_link3 -->
	<link name="joint_link3">
		<visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <cylinder length="${height}" radius=".05" />
            </geometry>
            <material name="white"/>
        </visual>
        
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<cylinder length="${height}" radius=".05" />
			</geometry>
		</collision>
		
		<inertial>
            <mass value="${mass}"/>
            <inertia ixx="${1}" ixy="0.0" ixz="0.0" 
                iyy="${1}" iyz="0.0" 
                izz="${1}"/>
        </inertial>
	</link>
	
</robot>
