<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot">

    <!--inertial.xacro 추가하기-->

	<!-- color -->

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="red">
        <color rgba="1 0.1 0.1 1"/>
    </material>

    <material name="green">
        <color rgba="0.1 1 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.1 0.1 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

	<!--  Constants   -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="mass" value="1" /> 
  <xacro:property name="width" value="0.1" /> 
  <xacro:property name="height" value="0.1" /> <!-- Joint Link -->
  <xacro:property name="height1" value="2" /> <!-- Link 1 -->
  <xacro:property name="height2" value="1" /> <!-- Link 2 -->
  <xacro:property name="height3" value="1" /> <!-- Link 3 -->

  <!-- xacro:property name="camera_link" value="0.1" /--> 
  <!-- xacro:property name="axel_offset" value="0.1" /--> 

	<!-- link -->
	
	<!-- Info. world -> Y,P joint - link1 - P joint - link2  - R,P,Y joint - link3       -->
	<!-- joint type : rev , fixed -->
	
	<!-- link 0. world link -->
	
	<link name="world"> 
	
	</link>
	
	<joint name="default" type="fixed">
		<parent link="world"/>
		<child link="joint_link1"/>
	</joint>

	<!-- link 1. Base Link -->
	<link name="joint_link1">
		<visual>
            <origin xyz="0 0 ${height/2}"/>
            <geometry>
                <box size="${width} ${width} ${height}"/>
            </geometry>
            <material name="white"/>
        </visual>
		<collision>
			<origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
			<geometry>
				<box size="${width} ${width} ${height}"/>
			</geometry>
		</collision>
	</link>
	
	
	<joint name="joint1" type="revolute">
		<parent link="world"/>
		<child link="joint_link1"/>
		<origin xyz="0 0 ${height}" />
        <axis xyz="0 0 1" />
        <limit effort="100" velocity="0.1" lower="-3.14" upper="3.14"/>
        <dynamics damping="50" friction="1"/>
	</joint>
	
</robot>
