controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true
# 업데이트 속도 및 시뮬레이션 시간 사용

#컨트롤러	1. 차량속도 컨트롤러
#			2. 조인트 상태 송출기
    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

#컨트롤러 상세정보 정의

diff_cont:
  ros__parameters:

    publish_rate: 50.0

    base_frame_id: base_link

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.35
    wheel_radius: 0.05

    use_stamped_vel: false

